#!/usr/bin/env bash

cp ~/Library/Application\ Support/Choosy/behaviours.plist $DOTFILES/prefs/choosy

cp ~/Library/Application\ Support/Sublime\ Text/Packages/User/*.sublime-settings $DOTFILES/prefs/sublime

cp ~/Library/Application\ Support/Audio\ Hijack\ 4/Sessions.plist $DOTFILES/prefs/audiohijack

cp /etc/hosts $DOTFILES/prefs/hosts
