#!/usr/bin/env bash

cp ~/Library/Application\ Support/Choosy/behaviours.plist $DOTFILES/prefs

cp ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/*.sublime-settings $DOTFILES/prefs/sublime
